import_environment {
  DOVEADM_PASSWORD = %{env:DOVEADM_PASSWORD | default)}
  USER_PASSWORD = %{env:USER_PASSWORD | default('{CRYPT}*')}
}

passdb static {
  password = %{env:USER_PASSWORD}
}

doveadm_password = $ENV:DOVEADM_PASSWORD
