#!/usr/bin/env bash

CFLAGS="-g -O2 -ffile-prefix-map=$PWD=. -fstack-clash-protection -mharden-sls=all -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
LDFLAGS=""

case $(uname -m) in
  x86_64)
    CFLAGS="$CFLAGS -mtune=generic -mavx -flto=auto -ffat-lto-objects -fcf-protection"
    LDFLAGS="-flto=auto -ffat-lto-objects"
  ;;
  aarch64|arm64)
    CFLAGS="$CFLAGS -mbranch-protection=standard"
    LDFLAGS=""
  ;;
esac

exec ./configure $* CFLAGS="$CFLAGS" LDFLAGS="-Wl,-Bsymbolic-functions $LDFLAGS" CXXFLAGS="$CFLAGS"
